# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Adriano Maciel
tagline:             'Senior Full Stack (Back end, Front end and Mobile) Programmer'
description:         'PHP Specialist, Ionic Developer, Front End Friendly and FullStack Man.'
url:                 https://adrianowead.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Adriano Maciel
  url:               https://adrianowead.github.io
  email:             

# Custom vars
version:             1.0.0
